Newer, better prune script Fixed some errors in backup script There exists a grep -c and it's better than wc -l

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -7,7 +7,7 @@
 # Sun Oct 24 22:39:55 CDT 2010
 
 # General purpose mailer subroutine. 
-mailreport() {
+function mailreport() {
     EMAILADDRESS=$1
     SUBJECT=$2
     MESSAGEFILE=$3
@@ -16,7 +16,7 @@ mailreport() {
 }
 
 # Expand rsync error codes
-expand_rsync_exit_code() {
+function expand_rsync_exit_code() {
         EXITCODE=$1
         case $EXITCODE in
             1) echo -e "Syntax or usage error";;
@@ -44,7 +44,7 @@ expand_rsync_exit_code() {
 
 # Resolve symlinks since "readlink -f" won't work on OS X
 # http://stackoverflow.com/a/1116890
-resolve_link() {
+function resolve_link() {
     TARGET_FILE=$1
 
     cd `dirname $TARGET_FILE`
@@ -65,8 +65,26 @@ resolve_link() {
     echo $RESULT
 }
 
+# Usage information
+function usage() {
+  echo -e "
+`basename $0` [OPTIONS]
+
+Options
+ -s   absolute path to source 
+ -d   backup destination
+ -t   type of backup: sync, snap or diff (default is 'snap')
+ -f   any extra flags to the rsync command (e.g. ssh)
+ -i   a file containing patterns to include in the backup
+ -e   a file containing patterns to exclude from the backup
+ -m   email address to mail reports to
+ -q   be quiet and show no output
+"
+  exit 
+}
+
 # Log the time started
-STARTDATE=`date "+%Y-%m-%dT%H.%M.%S"`
+TIME_STARTED=`date "+%Y-%m-%dT%H.%M.%S"`
 
 # Check for the mail command
 which mail &> /dev/null
@@ -82,26 +100,12 @@ if [ $? -ne 0 ]; then
     exit
 fi
 
-# Usage information
+# Show usage if no params
 if [ $# -eq 0 ]; then
-	echo -e "
-`basename $0` [OPTIONS]
-
-Options
- -s   absolute path to source 
- -d   backup destination
- -t   type of backup: sync, snap or diff
-      default is 'snap'
- -f   any extra flags to the rsync command (e.g. ssh)
- -i   a file containing patterns to include in the backup
- -e   a file containing patterns to exclude from the backup
- -m   email address to mail reports to
- -q   be quiet and show no output
-"
-	exit 
+  usage
 fi
 
-
+# Start collecting params
 BEQUIET=false
 EMAILADDRESS=""
 while getopts ":s:d:t:i:e:f:e:m:q" opt; do
@@ -145,39 +149,40 @@ while getopts ":s:d:t:i:e:f:e:m:q" opt; do
 done
 
 # Define log files for transfer reports. Define a process lock.
-EVENTLOG="/tmp/backuplog.$STARTDATE"
-TRANSFERLOG="/tmp/backuplog.$STARTDATE.full"
-SHORTLOG=$TARGET/'logs'/backuplog.$STARTDATE
-LONGLOG=$TARGET/'logs'/backuplog.$STARTDATE.full
+EVENTLOG="/tmp/backuplog.$TIME_STARTED"
+TRANSFERLOG="/tmp/backuplog.$TIME_STARTED.full"
+SHORTLOG=$TARGET/'logs'/backuplog.$TIME_STARTED
+LONGLOG=$TARGET/'logs'/backuplog.$TIME_STARTED.full
 LOCKFILE="/tmp/backuplock"
+SOURCESERVER=$(hostname -s)
 
 # Start logging
-echo -e "Started     : $STARTDATE"    >> $EVENTLOG
+echo -e "Started     : $TIME_STARTED"     > $EVENTLOG
 echo -e "Type        : $BACKUPOPTION" >> $EVENTLOG
 echo -e "Source      : $SOURCE"       >> $EVENTLOG
-echo -e "Host        : `hostname -s`" >> $EVENTLOG
+echo -e "Host        : $SOURCESERVER" >> $EVENTLOG
 echo -e "Destination : $TARGET"       >> $EVENTLOG
 
 # Does local source exist?
 if [ ! -d $SOURCE ]; then
-	echo -e "\nCould not find local source $SOURCE" >> $EVENTLOG
-        if [ "$EMAILADDRESS" != "" ]; then
-            mailreport $EMAILADDRESS "eror - $SOURCESERVER" $EVENTLOG
-        elif [ "$BEQUIET" == "false" ]; then
-            more $EVENTLOG
-        fi
-	exit
+  echo -e "\nCould not find local source $SOURCE" >> $EVENTLOG
+  if [ "$EMAILADDRESS" != "" ]; then
+      mailreport $EMAILADDRESS "eror - $SOURCESERVER" $EVENTLOG
+  elif [ "$BEQUIET" == "false" ]; then
+      more $EVENTLOG
+  fi
+  exit 1
 fi
 
 # Does the local target exist?
 if [ ! -d $TARGET ]; then
-	echo -e "\nTarget ($TARGET) does not exist" >> $EVENTLOG
-        if [ "$EMAILADDRESS" != "" ]; then
-            mailreport $EMAILADDRESS "eror - $SOURCESERVER" $EVENTLOG
-        elif [ "$BEQUIET" == "false" ]; then
-            more $EVENTLOG
-        fi
-	exit
+  echo -e "\nTarget ($TARGET) does not exist" >> $EVENTLOG
+  if [ "$EMAILADDRESS" != "" ]; then
+      mailreport $EMAILADDRESS "eror - $SOURCESERVER" $EVENTLOG
+  elif [ "$BEQUIET" == "false" ]; then
+      more $EVENTLOG
+  fi
+  exit 1
 fi
 
 # Valid rsync option specified? (TODO: investigate why using || didn't work...)
@@ -194,7 +199,7 @@ if [ ! -z $BACKUPOPTION ]; then
                     more $EVENTLOG
                 fi
 
-                exit
+                exit 1
             fi
         fi
     fi
@@ -204,10 +209,10 @@ fi
 
 # Check for an includes file
 if [ -e "$BACKUPINCLUDESFILE" ] && [ -f $BACKUPINCLUDESFILE ]; then
-	INCLUDESFLAG="--include-from=$BACKUPINCLUDESFILE"
-	echo -e "Includes    : $BACKUPINCLUDESFILE" >> $EVENTLOG
+  INCLUDESFLAG="--include-from=$BACKUPINCLUDESFILE"
+  echo -e "Includes    : $BACKUPINCLUDESFILE" >> $EVENTLOG
 else
-	INCLUDESFLAG=""
+  INCLUDESFLAG=""
 fi
 
 # Check for an excludes file
@@ -220,17 +225,15 @@ fi
 
 # Check if a competing backup process exists
 if [ -e "$LOCKFILE" ]; then
-	echo -e "\nAnother backup job exists for the same client. Aborting." >> $EVENTLOG
-
-        if [ "$EMAILADDRESS" != "" ]; then
-            mailreport $EMAILADDRESS "eror - $SOURCESERVER" $EVENTLOG
-        elif [ "$BEQUIET" == "false" ]; then
-            more $EVENTLOG
-        fi
-
-	exit
+  echo -e "\nAnother backup job exists for the same client. Aborting." >> $EVENTLOG
+  if [ "$EMAILADDRESS" != "" ]; then
+      mailreport $EMAILADDRESS "eror - $SOURCESERVER" $EVENTLOG
+  elif [ "$BEQUIET" == "false" ]; then
+      more $EVENTLOG
+  fi
+  exit 1
 else
-	touch $LOCKFILE
+  touch $LOCKFILE
 fi
 
 ##### E N D  S A N I T Y   C H E C K #####
@@ -238,7 +241,7 @@ fi
 # Start some initial setup. Make sure that source-named directory exists at target
 if [ ! -d $TARGET/'latest' ]; then
 
-	FIRSTBACKUP='true'
+  FIRSTBACKUP='true'
         echo -e "Full Backup : Yes" >> $EVENTLOG
 else
         echo -e "Full Backup : No" >> $EVENTLOG
@@ -246,7 +249,7 @@ fi
 
 # Make sure we have a place to put the final transfer log
 if [ ! -d $TARGET/'logs' ]; then
-	mkdir $TARGET/'logs'
+  mkdir $TARGET/'logs'
 fi
 
 # Start the catalog; columns are 15, 20, 20 (TODO: use sprintf?)
@@ -259,44 +262,44 @@ if [ "$FIRSTBACKUP" == "true" ]; then
 else
     echo -n $BACKUPOPTION"           " >> $CATALOG
 fi
-echo -n $STARTDATE"  " >> $CATALOG
+echo -n $TIME_STARTED"  " >> $CATALOG
 
 # Configure rsync command params based on backup type
 if [ "$BACKUPOPTION" == "sync" ]; then
 
         if [ "$FIRSTBACKUP" == "true" ]; then
-	        mkdir $TARGET/$STARTDATE
-	        BACKUPDIRECTORY=$TARGET/$STARTDATE
+          mkdir $TARGET/$TIME_STARTED
+          BACKUPDIRECTORY=$TARGET/$TIME_STARTED
         else
-	        BACKUPDIRECTORY=$TARGET/'latest'
+          BACKUPDIRECTORY=$TARGET/'latest'
         fi
 
-	LINKFLAG=""
-	DELETEFLAG="--delete"
+  LINKFLAG=""
+  DELETEFLAG="--delete"
 
 elif [ "$BACKUPOPTION" == "snap" ]; then
 
-	if [ ! -d $TARGET/$STARTDATE ]; then
-		mkdir $TARGET/$STARTDATE
-	fi
+  if [ ! -d $TARGET/$TIME_STARTED ]; then
+    mkdir $TARGET/$TIME_STARTED
+  fi
 
-	BACKUPDIRECTORY=$TARGET/$STARTDATE
+  BACKUPDIRECTORY=$TARGET/$TIME_STARTED
 
-	# Set the hard link flag since we're taking snapshots
-	if [ "$FIRSTBACKUP" != "true" ]; then
-		LINKFLAG="--link-dest=$TARGET/latest/"
-	else
-		LINKFLAG=""
-	fi
-	DELETEFLAG=""
+  # Set the hard link flag since we're taking snapshots
+  if [ "$FIRSTBACKUP" != "true" ]; then
+    LINKFLAG="--link-dest=$TARGET/latest/"
+  else
+    LINKFLAG=""
+  fi
+  DELETEFLAG=""
 
 else
 
-	if [ ! -d $TARGET/$STARTDATE ]; then
-		mkdir $TARGET/$STARTDATE
-	fi
+  if [ ! -d $TARGET/$TIME_STARTED ]; then
+    mkdir $TARGET/$TIME_STARTED
+  fi
 
-	BACKUPDIRECTORY=$TARGET/$STARTDATE
+  BACKUPDIRECTORY=$TARGET/$TIME_STARTED
 
     if [ "$FIRSTBACKUP" != "true" ]; then
         # Add a message to the transfer log to differentiate 'diff' from 'snap'
@@ -305,7 +308,7 @@ else
     else
         LINKFLAG=""
     fi
-	DELETEFLAG=""
+  DELETEFLAG=""
 
 fi
 
@@ -316,7 +319,7 @@ rsync -avh --no-whole-file --numeric-ids --progress --stats $INCLUDESFLAG $LINKF
 RSYNCEXITCODE=$?
 
 # Log finish time
-FINISHTIME=`date "+%Y-%m-%dT%H.%M.%S"`
+TIME_FINISHED=`date "+%Y-%m-%dT%H.%M.%S"`
 
 # Descend into target directory
 cd $TARGET
@@ -334,11 +337,11 @@ if [ $RSYNCEXITCODE -eq 0 ] || [ $RSYNCEXITCODE -eq 23 ] || [ $RSYNCEXITCODE -eq
     EMAILSUBJECT="$BACKUPOPTION - `hostname -s`"
 
     # Log when most of the process is complete
-    echo $FINISHTIME"  " >> $CATALOG
+    echo $TIME_FINISHED"  " >> $CATALOG
 
-    echo -e "Summary Log  : $SHORTLOG.gz" >> $EVENTLOG
-    echo -e "Transfer Log : $LONGLOG.gz" >> $EVENTLOG
-    echo -e "Finished     : $FINISHTIME" >> $EVENTLOG
+    echo -e "Summary Log : $SHORTLOG.gz" >> $EVENTLOG
+    echo -e "Transfer Log: $LONGLOG.gz"  >> $EVENTLOG
+    echo -e "Finished    : $TIME_FINISHED"  >> $EVENTLOG
 
     # Log reference directory if incremental backup
     if [ "$BACKUPOPTION" == "diff" ]; then
@@ -348,7 +351,7 @@ if [ $RSYNCEXITCODE -eq 0 ] || [ $RSYNCEXITCODE -eq 23 ] || [ $RSYNCEXITCODE -eq
     # Or the number of snapshots 
     elif [ "$BACKUPOPTION" == "snap" ]; then
         echo -e "\n---- Other notes ----\n" >> $EVENTLOG
-        SNAPSHOTNUMBER=$(find $TARGET -maxdepth 1 -type d | sort | grep '\<[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}T[0-9]\{2\}\.[0-9]\{2\}\.[0-9]\{2\}\>' | wc -l)
+        SNAPSHOTNUMBER=$(find $TARGET -maxdepth 1 -type d | sort | grep -c '\<[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}T[0-9]\{2\}\.[0-9]\{2\}\.[0-9]\{2\}\>')
         echo -e "There exist $SNAPSHOTNUMBER snapshot(s) at the destination" >> $EVENTLOG
     fi
 
@@ -360,6 +363,7 @@ if [ $RSYNCEXITCODE -eq 0 ] || [ $RSYNCEXITCODE -eq 23 ] || [ $RSYNCEXITCODE -eq
     echo -e "\n---- Drive Map  ----\n" >> $EVENTLOG
     df -ah >> $EVENTLOG
 
+    # Email if specified
     if [ "$EMAILADDRESS" != "" ]; then
         mailreport $EMAILADDRESS "$EMAILSUBJECT" $EVENTLOG
     elif [ "$BEQUIET" == "false" ]; then
@@ -369,23 +373,23 @@ if [ $RSYNCEXITCODE -eq 0 ] || [ $RSYNCEXITCODE -eq 23 ] || [ $RSYNCEXITCODE -eq
     # Copy log files to their intended destination and compress them
     mv $EVENTLOG $SHORTLOG
     mv $TRANSFERLOG $LONGLOG
-    gzip $SHORTLOG $LONGLOG
+    gzip -9 $SHORTLOG $LONGLOG
 
     # Finally, move the 'latest' symlink
     if [ -s 'latest' ]; then
         if [ "$BACKUPOPTION" == "sync" ]; then
             LASTSYNCPATH=$(resolve_link latest)
-            mv $LASTSYNCPATH $TARGET/$STARTDATE
+            mv $LASTSYNCPATH $TARGET/$TIME_STARTED
         fi
         rm 'latest'
     fi
-    ln -s $STARTDATE 'latest'
+    ln -s $TIME_STARTED 'latest'
 
 # Errors encountered, so:
 else
 
     # Rename the target directory
-    mv $STARTDATE $STARTDATE.incomplete
+    mv $TIME_STARTED $TIME_STARTED.incomplete
 
     # Prepare depressing email subject
     EMAILSUBJECT="eror - `hostname -s`" 
@@ -414,3 +418,4 @@ fi
 
 # Remove lock file
 rm $LOCKFILE
+exit 0
diff --git a/prune b/prune
--- a/prune
+++ b/prune
@@ -3,210 +3,213 @@
 # Maintain 'n' number of snapshots at any given time. 
 # Complimentary to backup
 # https://github.com/afreeorange/rsync-timemachine
-# This needs a MASSIVE rewrite
 
 # Nikhil Anand <anand.nikhil@gmail.com>
 # Mon Oct 25 09:22:28 CDT 2010
 
 # General purpose mailer subroutine. 
-mailreport() {
-        ADMINEMAIL="admin@localhost"
-        SUBJECTSTUB=$1
-        MESSAGEFILE=$2
+function mailreport() {
+    EMAILADDRESS=$1
+    SUBJECT=$2
+    MESSAGEFILE=$3
 
-        mail -s "rote - $SUBJECTSTUB" $ADMINEMAIL < $MESSAGEFILE
+    mail -s "$SUBJECT" $EMAILADDRESS < $MESSAGEFILE
 }
 
 # Emulate the 'seq' command for OS X. This _could_ be done with 'jot', but I'm le lazy.
-function mac_seq() {
-	counter="$1"
-	max="$2"
+function _seq() {
+  counter="$1"
+  max="$2"
 
-	if [ "$#" -eq 2 ] ; then
-	  step=1
-	else
-	  step=$3
-	fi
+  if [ "$#" -eq 2 ] ; then
+    step=1
+  else
+    step=$3
+  fi
 
-	while [ $counter -le $max ] ; do
-	  echo $counter
-	  counter=$(expr $counter + $step)
-	done
+  while [ $counter -le $max ] ; do
+    echo $counter
+    counter=$(expr $counter + $step)
+  done
 
-	return 0
+  return 0
 }
 
-# A little information
-if [ $# -lt 2 ]; then
-	echo -e "Usage: `basename $0` <backup target> <no. of snapshots>"
-	echo -e "       Will look for snapshots formatted like yyyy-mm-ddThh.mm.ss"
-        echo -e "       An example is any file or directory with \"2010-08-09T16.01.28\" in its name"
-	echo -e "       If it exists, the 'logs' folder will be cleaned too"
-	exit
-fi
+# Show script usage information
+function usage() {
+  echo -e "
+`basename $0` [OPTIONS]
+
+Options
+ -d   backup directory containing snapshots
+ -n   number of snapshots to keep (default 10)
+ -r   remove old rotation logs (default)
+ -m   email address to mail reports to
+ -q   be quiet and show no output
+"
+  exit
+}
+
+# Show usage if no params
+[[ $# -eq 0 ]] && usage
+
+# Start collecting rotation params
+BEQUIET=false
+EMAILADDRESS=""
+while getopts "d:n:rm:q" opt; do
+  case $opt in
+    d)
+      SNAPSHOT_FOLDER=$OPTARG
+      ;;
+    n)
+      NUMBER_TO_KEEP=$OPTARG
+      ;;
+    r)
+      DELETE_ROTATION_LOGS=true
+      ;;
+    m)
+      EMAILADDRESS=$OPTARG
+      ;;
+    q)
+      BEQUIET=true
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
+  esac
+done
 
 # Log the start time
-STARTDATE=`date "+%Y-%m-%dT%H.%M.%S"`
+TIME_STARTED=`date "+%Y-%m-%dT%H.%M.%S"`
 
 # Set the internal file separator since we're using arrays
 IFS='
 '
-# Collect params
-LOCALBACKUPTARGET=$1
-SNAPSHOTNUMBER=$2
 
-# Define a log file; accommodate backup scripts that don't create logs
-if [ ! -d $LOCALBACKUPTARGET/'logs' ]; then
-       ROTATELOG=/tmp/rotatelog.$STARTDATE
-else
-       ROTATELOG="$LOCALBACKUPTARGET/logs/rotatelog.$STARTDATE"
-fi
+# Define log files, process lock, etc
+ROTATELOG="/tmp/rotatelog.$TIME_STARTED"
+DELETELOG=$(mktemp $ROTATELOG.XXXXXX)
+LOCKFILE="/tmp/rotatelock"
+SOURCESERVER=$(hostname -s)
+CATALOG="$SNAPSHOT_FOLDER/logs/catalog"
 
 # Start logging
-echo -e "Started         : $STARTDATE"         >> $ROTATELOG
-echo -e "Target          : $LOCALBACKUPTARGET" >> $ROTATELOG
-echo -e "Logfile         : $ROTATELOG"         >> $ROTATELOG
-echo -e "No. to maintain : $SNAPSHOTNUMBER"    >> $ROTATELOG
+echo -e "Started     : $TIME_STARTED"    >> $ROTATELOG
+echo -e "Backup path : $SNAPSHOT_FOLDER" >> $ROTATELOG
 
 ###### BEGIN SANITY CHECK #####
 
+# Check the number of snapshots specified
+if [ -z $NUMBER_TO_KEEP ]; then
+  NUMBER_TO_KEEP=10
+fi
+case "$NUMBER_TO_KEEP" in
+  *[!0-9]*) NUMBER_TO_KEEP=10 ;;
+         0) NUMBER_TO_KEEP=10
+esac
+
 # Check for the existence of the backup folder 
-if [ ! -d $LOCALBACKUPTARGET ]; then
-        echo -e "\n---- Error ----\n" >> $ROTATELOG
-	echo -e "Could not find backup folder $LOCALBACKUPTARGET" >> $ROTATELOG
-        mailreport "Error - Rotation - $LOCALBACKUPTARGET" $ROTATELOG
-        mv $ROTATELOG{,.error}
-	exit
+if [ ! -d $SNAPSHOT_FOLDER ]; then
+  echo -e "\nCould not find source $SNAPSHOT_FOLDER" >> $ROTATELOG
+  if [ ! -z $EMAILADDRESS ]; then
+      mailreport $EMAILADDRESS "eror - $SOURCESERVER" $ROTATELOG
+  elif [ ! -z $BEQUIET ]; then
+      more $ROTATELOG
+  fi
+  exit 1
 fi
 
-# Get the number of backup entities (dirs and logdirs)
-BACKUPNUMBER=$(find $LOCALBACKUPTARGET      -maxdepth 1         | sort | grep '\<[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}T[0-9]\{2\}\.[0-9]\{2\}\.[0-9]\{2\}\>' | wc -l)
-LOGLIST=($(find     $LOCALBACKUPTARGET/logs -maxdepth 1 -type f | sort | grep '\<.*backuplog.[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}T[0-9]\{2\}\.[0-9]\{2\}\.[0-9]\{2\}\>'))
-LOGNUMBER=$(find    $LOCALBACKUPTARGET/logs -maxdepth 1 -type f | sort | grep '\<.*backuplog.[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}T[0-9]\{2\}\.[0-9]\{2\}\.[0-9]\{2\}\>' | wc -l)
-LOGSTOMAINTAIN=$(($SNAPSHOTNUMBER * 2))
+# Generate a list of ISO timestamps. Will be used to find and delete snapshots and log files
+LIST_OF_TIMESTAMPS=($(find $SNAPSHOT_FOLDER -maxdepth 1 -type d | xargs basename | sort | grep '\<[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}T[0-9]\{2\}\.[0-9]\{2\}\.[0-9]\{2\}\>'))
+NUMBER_OF_SNAPSHOTS=${#LIST_OF_TIMESTAMPS[@]}
 
-# Nothing in the directory?
-if [ $BACKUPNUMBER -eq "0" ]; then
+echo -e "Snapshots   : $NUMBER_OF_SNAPSHOTS" >> $ROTATELOG
+echo -e "Keep        : $NUMBER_TO_KEEP"      >> $ROTATELOG
 
-    # TODO: Log files?
-
-    echo -e "\n---- Error ----\n" >> $ROTATELOG
-	echo -e "No backup entities found in the specified directory ($LOCALBACKUPTARGET)" >> $ROTATELOG
-
-	echo -e "Log file archived in $ROTATELOG.error" >> $ROTATELOG
-        mailreport "Error - Rotation - $LOCALBACKUPTARGET" $ROTATELOG
-        mv $ROTATELOG{,.error}
-	exit
-
-# If this is a 'sync' backup, we have one backup dir and MANY log files
-elif [ $BACKUPNUMBER -eq "1" ]; then
-        echo -e "Type of backup  : $LOCALBACKUPTARGET" >> $ROTATELOG
-        
-
-# More than one backup directory detected at this point; one last check
+# Check if any backup entities exist in source dir
+if [ $NUMBER_OF_SNAPSHOTS -eq "0" ]; then
+  echo -e "\nNo backup entities found in the specified directory ($SNAPSHOT_FOLDER)" >> $ROTATELOG
+  exit 1
 else
-    # More snapshots than existing directories?
-    if [ $SNAPSHOTNUMBER -ge $BACKUPNUMBER ]; then
-            echo -e "\n---- Error ----\n" >> $ROTATELOG
-            echo -e "Not enough entities exist ($BACKUPNUMBER) for requested snapshots ($SNAPSHOTNUMBER)" >> $ROTATELOG
-
-            echo -e "Log file archived in $ROTATELOG.error" >> $ROTATELOG
-            mailreport "Error - Rotation - $LOCALBACKUPTARGET" $ROTATELOG
-            mv $ROTATELOG{,.error}
-            exit
-    fi
+  # More snapshots than existing directories?
+  if [ $NUMBER_TO_KEEP -gt $NUMBER_OF_SNAPSHOTS ]; then
+    echo -e "\nYou wanted to keep $NUMBER_TO_KEEP snapshots out of $NUMBER_OF_SNAPSHOTS. Kinda not possible." >> $ROTATELOG
+    exit 1
+  elif [ $NUMBER_TO_KEEP -eq $NUMBER_OF_SNAPSHOTS ]; then
+    echo -e "\nYou want to delete $NUMBER_TO_KEEP out of $NUMBER_OF_SNAPSHOTS snapshots? Why not just remove the backup directory and be done? Why mess with me?" >> $ROTATELOG
+    exit 1
+  fi
 fi
-
-# Cheekiness?
-if [ $SNAPSHOTNUMBER -eq "0" ]; then
-        echo -e "\n---- Error ----\n" >> $ROTATELOG
-	echo -e "Think of specifying zero as a snapshot number.." >> $ROTATELOG
-	echo -e "Look at it and tell me if there's a point to running this script... smartass." >> $ROTATELOG
-
-	echo -e "Log file archived in $ROTATELOG.error" >> $ROTATELOG
-        mailreport "Error - Rotation - $LOCALBACKUPTARGET" $ROTATELOG
-        mv $ROTATELOG{,.error}
-	exit
-fi
-
+  
 # Check platform and set the seq command 
+SEQUENCE=_seq
 if [ `uname` == "Linux" ]; then
-        SEQ_COMMAND=$(which seq)
+  SEQUENCE=$(which seq)
+fi
+
+# Check if a competing backup process exists
+if [ -e "$LOCKFILE" ]; then
+  echo -e "\nAnother rotation job exists for the same client. Aborting." >> $ROTATELOG
+  if [ "$EMAILADDRESS" != "" ]; then
+      mailreport $EMAILADDRESS "eror - $SOURCESERVER" $ROTATELOG
+  elif [ "$BEQUIET" == "false" ]; then
+      more $ROTATELOG
+  fi
+  exit 1
 else
-        SEQ_COMMAND=mac_seq
+  touch $LOCKFILE
 fi
 
 ###### END SANITY CHECK ######
 
-# Collect a list of backup entities. Assumed that they are in YYYY-MM-DDTHH.MM.SSZ (ISO8601) format
-DIRLIST=($(find $LOCALBACKUPTARGET -maxdepth 1 | sort | grep '\<[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}T[0-9]\{2\}\.[0-9]\{2\}\.[0-9]\{2\}\>'))
-echo -e "No. of backups  : $BACKUPNUMBER" >> $ROTATELOG
+# Seems like everything is okay; start deleting. Create a temporary deletion log
+echo -e "\n---- Removal Log ----\n" >> $DELETELOG
+CLEAN_TO_INDEX=$(( NUMBER_OF_SNAPSHOTS - NUMBER_TO_KEEP - 1 ))
+for i in $($SEQUENCE 0 $CLEAN_TO_INDEX); do
+  rm -rf $SNAPSHOT_FOLDER/${LIST_OF_TIMESTAMPS[i]} 2>> $DELETELOG
+  echo "Removed" $SNAPSHOT_FOLDER/${LIST_OF_TIMESTAMPS[i]} >> $DELETELOG
 
-# Define a temporary removal log
-TEMPLOG=$(mktemp /tmp/XXXXXXXX)
-echo -e "Removal log     : $TEMPLOG"           >> $ROTATELOG
-echo -e "\n----- Begin removal log -----\n\nFound Entities:" >> $TEMPLOG
+  rm -rf $SNAPSHOT_FOLDER/logs/backuplog.${LIST_OF_TIMESTAMPS[i]}.gz 2>> $DELETELOG
+  echo "       " $SNAPSHOT_FOLDER/logs/${LIST_OF_TIMESTAMPS[i]}.full.gz >> $DELETELOG
 
-# Seems like everything is okay; start deleting and logging the directory deleted
-NUMBERCLEANED=$(( BACKUPNUMBER - SNAPSHOTNUMBER - 1 ))
-for i in $($SEQ_COMMAND 0 $NUMBERCLEANED); do
-	echo ${DIRLIST[i]} >> $TEMPLOG
-	chmod -R ug+rwx ${DIRLIST[i]}
-	rm -rf ${DIRLIST[i]}
+  rm -rf $SNAPSHOT_FOLDER/logs/backuplog.${LIST_OF_TIMESTAMPS[i]}.full.gz 2>> $DELETELOG
+  echo "       " $SNAPSHOT_FOLDER/logs/${LIST_OF_TIMESTAMPS[i]}.gz >> $DELETELOG
 done
 
-# Prepare list of directories which are left
-echo -e "\nThe following still exist:" >> $TEMPLOG
-find $LOCALBACKUPTARGET -maxdepth 1 | sort | grep '\<[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}T[0-9]\{2\}\.[0-9]\{2\}\.[0-9]\{2\}\>' >> $TEMPLOG
-
-# Now start removing backup logs, if they exist
-if [ -d $LOCALBACKUPTARGET/'logs' ]; then
-    echo -e "\nRemoving old backup logs" >> $TEMPLOG
-
-    # Since there is a summary and full log for each backup, a little arithmetic is necessary
-    LOGLIST=($(find $LOCALBACKUPTARGET/logs -maxdepth 1 -type f | sort | grep '\<.*backuplog.[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}T[0-9]\{2\}\.[0-9]\{2\}\.[0-9]\{2\}\>'))
-    LOGNUMBER=$(find $LOCALBACKUPTARGET/logs -maxdepth 1 -type f | sort | grep '\<.*backuplog.[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}T[0-9]\{2\}\.[0-9]\{2\}\.[0-9]\{2\}\>' | wc -l)
-    LOGSTOMAINTAIN=$(($SNAPSHOTNUMBER * 2))
-
-    # Start removing snapshot logs
-    for i in $($SEQ_COMMAND 0 $(( LOGNUMBER - LOGSTOMAINTAIN - 1 ))); do
-            echo ${LOGLIST[i]} >> $TEMPLOG
-            chmod -R ug+rwx ${LOGLIST[i]}
-            rm -rf ${LOGLIST[i]}
-    done
-
-    # Now clean the rotation logs
-    echo -e "\nCleaning old rotation log(s), if any..." >> $TEMPLOG
-    find $LOCALBACKUPTARGET/logs -maxdepth 1 -type f | sort | grep '\<rotatelog.[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}T[0-9]\{2\}\.[0-9]\{2\}\.[0-9]\{2\}\>' >> $TEMPLOG
-    find $LOCALBACKUPTARGET/logs -maxdepth 1 -type f | sort | grep '\<rotatelog.[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}T[0-9]\{2\}\.[0-9]\{2\}\.[0-9]\{2\}\>' | grep -v $ROTATELOG | xargs rm -rf
+# Remove older rotation logs
+if [ ! -z $DELETE_ROTATION_LOGS ]; then
+  rm -rf $SNAPSHOT_FOLDER/logs/rotatelog* 2>> $DELETELOG
 fi
 
 # Log finish time
-FINISHTIME=`date "+%Y-%m-%dT%H.%M.%S"`
-echo -e "Finished        : $FINISHTIME" >> $ROTATELOG
+TIME_FINISHED=`date "+%Y-%m-%dT%H.%M.%S"`
+echo -e "Finished    : $TIME_FINISHED" >> $ROTATELOG
 
-# Since we're rotating, a catalog must exit (of type SERVERNAME.catalog)
-CATALOG="$LOCALBACKUPTARGET/logs/catalog"
-if [ -e $CATALOG ]; then
-    echo -n "rote " >> $CATALOG
-    CATALOGCOUNT=$(printf "(%3d,%3d)" $BACKUPNUMBER $SNAPSHOTNUMBER)
-    echo -n $CATALOGCOUNT" " >> $CATALOG
-    echo -n $STARTDATE"  "   >> $CATALOG
-    echo $FINISHTIME"  "     >> $CATALOG
-else
-    echo "\nCould not append operation to catalog in $LOCALBACKUPTARGET/logs/; file does not exist!" >> $TEMPLOG
+# Finish the rotation log
+cat $DELETELOG >> $ROTATELOG
+
+# Email if specified
+if [ "$EMAILADDRESS" != "" ]; then
+  mailreport $EMAILADDRESS "$EMAILSUBJECT" $ROTATELOG
+elif [ "$BEQUIET" == "false" ]; then
+  cat $ROTATELOG
 fi
 
-# Append the removal log to the full log and remove it
-cat $TEMPLOG >> $ROTATELOG
-rm -f $TEMPLOG
+# Clean up
+rm -f $DELETELOG
+mv $ROTATELOG $SNAPSHOT_FOLDER/logs/rotatelog.$TIME_STARTED
+gzip -9 $SNAPSHOT_FOLDER/logs/rotatelog.$TIME_STARTED
 
-# Email the administrator
-mailreport "$LOCALBACKUPTARGET" $ROTATELOG
+# Finish the catalog
+echo -n "rote " >> $CATALOG
+CATALOGCOUNT=$(printf "(%3d,%3d) %s  %s" $NUMBER_OF_SNAPSHOTS $NUMBER_TO_KEEP $TIME_STARTED $TIME_FINISHED)
+echo $CATALOGCOUNT >> $CATALOG
 
-# Gzip or delete the log file
-if [ ! -d $LOCALBACKUPTARGET/'logs' ]; then
-        rm -f $ROTATELOG
-else
-        gzip -9 $ROTATELOG
-fi
+# Remove lock
+rm $LOCKFILE
+exit 0
