Shellcheck, editorconfig, README updates

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -6,39 +6,39 @@
 # by Nikhil Anand <nikhil@mantralay.org>
 # Sun Oct 22 22:39:55 CDT 2010
 
-# General purpose mailer subroutine. 
+# General purpose mailer subroutine.
 mailreport() {
   EMAILADDRESS=$1
   SUBJECT=$2
   MESSAGEFILE=$3
 
-  mail -s "$SUBJECT" $EMAILADDRESS < $MESSAGEFILE
+  mail -s "$SUBJECT" "$EMAILADDRESS" <"$MESSAGEFILE"
 }
 
 # Expand rsync error codes
 expand_rsync_exit_code() {
   EXITCODE=$1
   case $EXITCODE in
-    1) echo -e "Syntax or usage error";;
-    2) echo -e "Protocol incompatibility";;
-    3) echo -e "Errors selecting input/output files, dirs";;
-    4) echo -e "Requested  action not supported: an attempt was made to manipulate 64-bit files on a platform that cannot support them; or an option was specified that is supported by the client and not by the server.";;
-    5) echo -e "Error starting client-server protocol";;
-    6) echo -e "Daemon unable to append to log-file";;
-   10) echo -e "Error in socket I/O";;
-   11) echo -e "Error in file I/O";;
-   12) echo -e "Error in rsync protocol data stream (insufficient disk space?)";;
-   13) echo -e "Errors with program diagnostics";;
-   14) echo -e "Error in IPC code";;
-   20) echo -e "Received SIGUSR1 or SIGINT";;
-   21) echo -e "Some error returned by waitpid()";;
-   22) echo -e "Error allocating core memory buffers";;
-   23) echo -e "Partial transfer due to error";;
-   22) echo -e "Partial transfer due to vanished source files (might be normal)";;
-   25) echo -e "The --max-delete limit stopped deletions";;
-   30) echo -e "Timeout in data send/receive";;
-   35) echo -e "Timeout waiting for daemon connection";;
-    *) echo -e "Unknown; most likely a SIGINT (e.g. keyboard interrupt)";;
+  1) echo -e "Syntax or usage error" ;;
+  2) echo -e "Protocol incompatibility" ;;
+  3) echo -e "Errors selecting input/output files, dirs" ;;
+  4) echo -e "Requested  action not supported: an attempt was made to manipulate 64-bit files on a platform that cannot support them; or an option was specified that is supported by the client and not by the server." ;;
+  5) echo -e "Error starting client-server protocol" ;;
+  6) echo -e "Daemon unable to append to log-file" ;;
+  10) echo -e "Error in socket I/O" ;;
+  11) echo -e "Error in file I/O" ;;
+  12) echo -e "Error in rsync protocol data stream (insufficient disk space?)" ;;
+  13) echo -e "Errors with program diagnostics" ;;
+  14) echo -e "Error in IPC code" ;;
+  20) echo -e "Received SIGUSR1 or SIGINT" ;;
+  21) echo -e "Some error returned by waitpid()" ;;
+  22) echo -e "Error allocating core memory buffers" ;;
+  23) echo -e "Partial transfer due to error" ;;
+  24) echo -e "Partial transfer due to vanished source files (might be normal)" ;;
+  25) echo -e "The --max-delete limit stopped deletions" ;;
+  30) echo -e "Timeout in data send/receive" ;;
+  35) echo -e "Timeout waiting for daemon connection" ;;
+  *) echo -e "Unknown; most likely a SIGINT (e.g. keyboard interrupt)" ;;
   esac
 }
 
@@ -47,28 +47,27 @@ expand_rsync_exit_code() {
 resolve_link() {
   TARGET_FILE=$1
 
-  cd `dirname $TARGET_FILE`
-  TARGET_FILE=`basename $TARGET_FILE`
+  cd "$(dirname "$TARGET_FILE")" || exit 36
+  TARGET_FILE=$(basename "$TARGET_FILE")
 
   # Iterate down a (possible) chain of symlinks
-  while [ -L "$TARGET_FILE" ]
-  do
-  TARGET_FILE=`readlink $TARGET_FILE`
-  cd `dirname $TARGET_FILE`
-  TARGET_FILE=`basename $TARGET_FILE`
+  while [ -L "$TARGET_FILE" ]; do
+    TARGET_FILE=$(readlink "$TARGET_FILE")
+    cd "$(dirname "$TARGET_FILE")" || exit 37
+    TARGET_FILE=$(basename "$TARGET_FILE")
   done
 
-  # Compute the canonicalized name by finding the physical path 
+  # Compute the canonicalized name by finding the physical path
   # for the directory we're in and appending the target file.
-  PHYS_DIR=`pwd -P`
+  PHYS_DIR=$(pwd -P)
   RESULT=$PHYS_DIR/$TARGET_FILE
-  echo $RESULT
+  echo "$RESULT"
 }
 
 # Usage information
 usage() {
   echo -e "
-`basename $0` [OPTIONS]
+$(basename "$0") [OPTIONS]
 
 Options
  -s   absolute path to source 
@@ -81,7 +80,7 @@ Options
  -m   email address to mail reports to
  -q   be quiet and show no output
 "
-  exit 
+  exit
 }
 
 # Send nicely formatted backup params to log
@@ -90,26 +89,22 @@ send_log_param() {
 }
 
 # Log the time started
-TIME_STARTED=`date "+%Y-%m-%dT%H.%M.%S"`
+TIME_STARTED=$(date "+%Y-%m-%dT%H.%M.%S")
 
 # Check for the mail command
-which mail &> /dev/null
-if [ $? -ne 0 ]; then
-  echo -e "mail command not found. Aborting" 
-  exit
-fi
+command -v mail >/dev/null || {
+  echo -e "mail command not found. Aborting"
+  exit 1
+}
 
 # Check for rsync
-which rsync &> /dev/null
-if [ $? -ne 0 ]; then
+command -v rsync >/dev/null || {
   echo -e "rsync command not found. Aborting"
-  exit
-fi
+  exit 1
+}
 
 # Show usage if no params
-if [ $# -eq 0 ]; then
-  usage
-fi
+[[ $# -eq 0 ]] && usage
 
 # Start collecting params
 BEQUIET=false
@@ -138,9 +133,6 @@ while getopts ":s:d:t:xi:e:f:e:m:q" opt; do
   f)
     EXTRAFLAGS=$OPTARG
     ;;
-  p)
-    SSHPORT=$OPTARG
-    ;;
   m)
     EMAILADDRESS=$OPTARG
     ;;
@@ -167,46 +159,48 @@ LOCKFILE="/tmp/backuplock"
 SOURCESERVER=$(hostname -s)
 
 # Check that a source and target have been specified at a minimum
-if [ -z $SOURCE ] || [ -z $TARGET ]; then
+if [[ -z $SOURCE ]] || [[ -z $TARGET ]]; then
   echo -e "! You must specify a source (-s) and target (-d) at a minimum"
   usage
   exit 1
 fi
 
 # Does local source exist?
-if [ ! -d $SOURCE ]; then
-  echo -e "\nCould not find local source $SOURCE" >> $EVENTLOG
-  if [ "$EMAILADDRESS" != "" ]; then
-    mailreport $EMAILADDRESS "eror - $SOURCESERVER" $EVENTLOG
-  elif [ "$BEQUIET" == "false" ]; then
-    more $EVENTLOG
+if [[ ! -d $SOURCE ]]; then
+  echo -e "\nCould not find local source $SOURCE" >>"$EVENTLOG"
+  if [[ "$EMAILADDRESS" != "" ]]; then
+    mailreport "$EMAILADDRESS" "eror - $SOURCESERVER" "$EVENTLOG"
+  elif [[ "$BEQUIET" == "false" ]]; then
+    more "$EVENTLOG"
   fi
   exit 1
 fi
 
 # Does the local target exist?
-if [ ! -d $TARGET ]; then
-  echo -e "\nTarget ($TARGET) does not exist" >> $EVENTLOG
-  if [ "$EMAILADDRESS" != "" ]; then
-    mailreport $EMAILADDRESS "eror - $SOURCESERVER" $EVENTLOG
-  elif [ "$BEQUIET" == "false" ]; then
-    more $EVENTLOG
+if [[ ! -d $TARGET ]]; then
+  echo -e "\nTarget ($TARGET) does not exist" >>"$EVENTLOG"
+  if [[ "$EMAILADDRESS" != "" ]]; then
+    mailreport "$EMAILADDRESS" "eror - $SOURCESERVER" "$EVENTLOG"
+  elif [[ "$BEQUIET" == "false" ]]; then
+    more "$EVENTLOG"
   fi
   exit 1
 fi
 
 # Valid rsync option specified? (TODO: investigate why using || didn't work...)
-if [ ! -z $BACKUPOPTION ]; then
-  if [ "$BACKUPOPTION" != "sync" ]; then
-    if  [ "$BACKUPOPTION" != "snap" ]; then
-      if  [ "$BACKUPOPTION" != "diff" ]; then
-        echo -e "\nInvalid transfer option specified." >> $EVENTLOG
-        echo -e "Must be one of sync, snap, or diff" >> $EVENTLOG
-        if [ "$EMAILADDRESS" != "" ]; then
-          mailreport $EMAILADDRESS "eror - $SOURCESERVER" $EVENTLOG
-        elif [ "$BEQUIET" == "false" ]; then
-          more $EVENTLOG
+if [[ -n $BACKUPOPTION ]]; then
+  if [[ "$BACKUPOPTION" != "sync" ]]; then
+    if [[ "$BACKUPOPTION" != "snap" ]]; then
+      if [[ "$BACKUPOPTION" != "diff" ]]; then
+        echo -e "\nInvalid transfer option specified." >>"$EVENTLOG"
+        echo -e "Must be one of sync, snap, or diff" >>"$EVENTLOG"
+
+        if [[ "$EMAILADDRESS" != "" ]]; then
+          mailreport "$EMAILADDRESS" "eror - $SOURCESERVER" "$EVENTLOG"
+        elif [[ "$BEQUIET" == "false" ]]; then
+          more "$EVENTLOG"
         fi
+
         exit 1
       fi
     fi
@@ -217,42 +211,46 @@ fi
 
 # Long name for the catalog
 case $BACKUPOPTION in
-  "snap") BACKUPOPTIONLONG="snapshot" ;;
-  "sync") BACKUPOPTIONLONG="sync" ;;
-  "diff") BACKUPOPTIONLONG="pure incremental" ;;
+"snap") BACKUPOPTIONLONG="snapshot" ;;
+"sync") BACKUPOPTIONLONG="sync" ;;
+"diff") BACKUPOPTIONLONG="pure incremental" ;;
 esac
 
 # Start logging
-send_log_param "Started"     "$TIME_STARTED"  > $EVENTLOG
-send_log_param "Type"        "$BACKUPOPTION" >> $EVENTLOG
-send_log_param "Source"      "$SOURCE"       >> $EVENTLOG
-send_log_param "Host"        "$SOURCESERVER" >> $EVENTLOG
-send_log_param "Destination" "$TARGET"       >> $EVENTLOG
+{
+  send_log_param "Started" "$TIME_STARTED"
+  send_log_param "Type" "$BACKUPOPTION"
+  send_log_param "Source" "$SOURCE"
+  send_log_param "Host" "$SOURCESERVER"
+  send_log_param "Destination" "$TARGET"
+} >>"$EVENTLOG"
 
 # Check for an includes file
-if [ -e "$BACKUPINCLUDESFILE" ] && [ -f $BACKUPINCLUDESFILE ]; then
+if [[ -e "$BACKUPINCLUDESFILE" ]] && [[ -f "$BACKUPINCLUDESFILE" ]]; then
   INCLUDESFLAG="--include-from=$BACKUPINCLUDESFILE"
-  send_log_param "Includes" "$BACKUPINCLUDESFILE" >> $EVENTLOG
+  send_log_param "Includes" "$BACKUPINCLUDESFILE" >>"$EVENTLOG"
 else
   INCLUDESFLAG=""
 fi
 
 # Check for an excludes file
-if [ -e "$BACKUPEXCLUDESFILE" ] && [ -f $BACKUPEXCLUDESFILE ]; then
+if [[ -e "$BACKUPEXCLUDESFILE" ]] && [[ -f "$BACKUPEXCLUDESFILE" ]]; then
   EXCLUDESFLAG="--exclude-from=$BACKUPEXCLUDESFILE"
-  send_log_param "Excludes" "$BACKUPEXCLUDESFILE" >> $EVENTLOG
+  send_log_param "Excludes" "$BACKUPEXCLUDESFILE" >>"$EVENTLOG"
 else
   EXCLUDESFLAG=""
 fi
 
 # Check if a competing backup process exists
-if [ -e "$LOCKFILE" ]; then
-  echo -e "\nAnother backup job exists for the same client. Aborting." >> $EVENTLOG
-  if [ "$EMAILADDRESS" != "" ]; then
-    mailreport $EMAILADDRESS "eror - $SOURCESERVER" $EVENTLOG
-  elif [ "$BEQUIET" == "false" ]; then
-    more $EVENTLOG
+if [[ -e "$LOCKFILE" ]]; then
+  echo -e "\nAnother backup job exists for the same client. Aborting." >>"$EVENTLOG"
+
+  if [[ "$EMAILADDRESS" != "" ]]; then
+    mailreport "$EMAILADDRESS" "eror - $SOURCESERVER" "$EVENTLOG"
+  elif [[ "$BEQUIET" == "false" ]]; then
+    more "$EVENTLOG"
   fi
+
   exit 1
 else
   touch $LOCKFILE
@@ -261,68 +259,66 @@ fi
 ##### E N D  S A N I T Y   C H E C K #####
 
 # Start some initial setup. Make sure that source-named directory exists at target
-if [ ! -d $TARGET/'latest' ]; then
+if [[ ! -d "$TARGET/latest" ]]; then
   FIRSTBACKUP='true'
-  send_log_param "Full backup" "Yes" >> $EVENTLOG
+  send_log_param "Full backup" "Yes" >>"$EVENTLOG"
 else
-  send_log_param "Full backup" "No" >> $EVENTLOG
+  send_log_param "Full backup" "No" >>"$EVENTLOG"
 fi
 
 # Make sure we have a place to put the final transfer log
-if [ ! -d $TARGET/'logs' ]; then
-  mkdir $TARGET/'logs'
+if [[ ! -d "$TARGET/logs" ]]; then
+  mkdir "$TARGET/logs"
 fi
 
 # Start the catalog; columns are 15, 30, 20
 CATALOG=$TARGET/'logs'/catalog
-if [ ! -e $CATALOG ]; then
-  printf "%-22s%-22s%-22s\n" "Operation" "Started" "Finished" >> $CATALOG
+if [[ ! -e "$CATALOG" ]]; then
+  printf "%-22s%-22s%-22s\n" "Operation" "Started" "Finished" >>"$CATALOG"
 fi
-if [ "$FIRSTBACKUP" == "true" ]; then
-  printf "%-22s" "full backup" >> $CATALOG
+if [[ "$FIRSTBACKUP" == "true" ]]; then
+  printf "%-22s" "full backup" >>"$CATALOG"
 else
-  printf "%-22s" $BACKUPOPTIONLONG >> $CATALOG
+  printf "%-22s" "$BACKUPOPTIONLONG" >>"$CATALOG"
 fi
-printf "%-22s" $TIME_STARTED >> $CATALOG
+printf "%-22s" "$TIME_STARTED" >>"$CATALOG"
 
 # Configure rsync command params based on backup type
-if [ "$BACKUPOPTION" == "sync" ]; then
-  if [ "$PURESYNC" == "true" ]; then
+if [[ "$BACKUPOPTION" == "sync" ]]; then
+  if [[ "$PURESYNC" == "true" ]]; then
     BACKUPDIRECTORY=$TARGET
   else
-    if [ "$FIRSTBACKUP" == "true" ]; then
-      mkdir $TARGET/$TIME_STARTED
+    if [[ "$FIRSTBACKUP" == "true" ]]; then
+      mkdir "$TARGET/$TIME_STARTED"
       BACKUPDIRECTORY=$TARGET/$TIME_STARTED
     else
       BACKUPDIRECTORY=$TARGET/'latest'
     fi
   fi
+
   LINKFLAG=""
   DELETEFLAG="--delete"
 
-elif [ "$BACKUPOPTION" == "snap" ]; then
+elif [[ "$BACKUPOPTION" == "snap" ]]; then
 
-  if [ ! -d $TARGET/$TIME_STARTED ]; then
-    mkdir $TARGET/$TIME_STARTED
-  fi
-  BACKUPDIRECTORY=$TARGET/$TIME_STARTED
+  [[ ! -d "$TARGET/$TIME_STARTED" ]] && mkdir "$TARGET/$TIME_STARTED"
+  BACKUPDIRECTORY="$TARGET/$TIME_STARTED"
 
   # Set the hard link flag since we're taking snapshots
-  if [ "$FIRSTBACKUP" != "true" ]; then
+  if [[ "$FIRSTBACKUP" != "true" ]]; then
     LINKFLAG="--link-dest=$TARGET/latest/"
   else
     LINKFLAG=""
   fi
+
   DELETEFLAG=""
 
 else
 
-  if [ ! -d $TARGET/$TIME_STARTED ]; then
-    mkdir $TARGET/$TIME_STARTED
-  fi
-
+  [[ ! -d "$TARGET/$TIME_STARTED" ]] && mkdir "$TARGET/$TIME_STARTED"
   BACKUPDIRECTORY=$TARGET/$TIME_STARTED
-  if [ "$FIRSTBACKUP" != "true" ]; then
+
+  if [[ "$FIRSTBACKUP" != "true" ]]; then
     # Add a message to the transfer log to differentiate 'diff' from 'snap'
     DIFFMESSAGE=${DIFFMESSAGE}"Incremental-only option selected."
     LINKFLAG="-c --compare-dest=$TARGET/latest/"
@@ -335,107 +331,132 @@ else
 fi
 
 # Perform the actual transfer over SSH
-rsync -avh --no-whole-file --numeric-ids --progress --stats $INCLUDESFLAG $EXCLUDESFLAG $LINKFLAG $DELETEFLAG $EXTRAFLAGS "$SOURCE" "$BACKUPDIRECTORY" 2>&1 >> $TRANSFERLOG
+# shellcheck disable=SC2086
+rsync -avh \
+  --no-whole-file \
+  --numeric-ids \
+  --progress \
+  --stats \
+  $INCLUDESFLAG \
+  $EXCLUDESFLAG \
+  $LINKFLAG \
+  $DELETEFLAG \
+  $EXTRAFLAGS \
+  "$SOURCE" "$BACKUPDIRECTORY" >>"$TRANSFERLOG" 2>&1
 
 # Log the exit code
 RSYNCEXITCODE=$?
 
 # Log finish time
-TIME_FINISHED=`date "+%Y-%m-%dT%H.%M.%S"`
+TIME_FINISHED=$(date "+%Y-%m-%dT%H.%M.%S")
 
 # Descend into target directory
-cd $TARGET
+cd "$TARGET" || (echo "Could not descend into $TARGET" && exit)
 
 # Check for errors. If everything's okay:
-if [ $RSYNCEXITCODE -eq 0 ] || [ $RSYNCEXITCODE -eq 23 ] || [ $RSYNCEXITCODE -eq 22 ]; then
+if [[ $RSYNCEXITCODE -eq 0 ]] || [[ $RSYNCEXITCODE -eq 23 ]] || [[ $RSYNCEXITCODE -eq 22 ]]; then
 
   # For 'diff' transfers, rsync copies directories, even if there's nothing in them. Clean 'em up!
-  if [ "$BACKUPOPTION" == "diff" ]; then
+  if [[ "$BACKUPOPTION" == "diff" ]]; then
     # This could fail if 'find' doesn't have the -empty and -delete flags on certain systems...
-    find $TARGET/latest/ -depth -type d -empty -delete &> /dev/null
+    find "$TARGET/latest/" -depth -type d -empty -delete &>/dev/null
   fi
 
   # Prepare nice email subject
-  EMAILSUBJECT="$BACKUPOPTION - `hostname -s`"
+  EMAILSUBJECT="$BACKUPOPTION - $(hostname -s)"
 
   # Log when most of the process is complete
-  printf "%-22s\n" "$TIME_FINISHED" >> $CATALOG
-  send_log_param "Summary Log"  "$SHORTLOG.gz"   >> $EVENTLOG
-  send_log_param "Transfer Log" "$LONGLOG.gz"    >> $EVENTLOG
-  send_log_param "Finished"     "$TIME_FINISHED" >> $EVENTLOG
+  printf "%-22s\n" "$TIME_FINISHED" >>"$CATALOG"
+
+  {
+    send_log_param "Summary Log" "$SHORTLOG.gz"
+    send_log_param "Transfer Log" "$LONGLOG.gz"
+    send_log_param "Finished" "$TIME_FINISHED"
+  } >>"$EVENTLOG"
 
   # Log reference directory if incremental backup
-  if [ "$BACKUPOPTION" == "diff" ]; then
-    echo -e "\n---- Other notes ----\n" >> $EVENTLOG
-    echo $DIFFMESSAGE >> $EVENTLOG
+  if [[ "$BACKUPOPTION" == "diff" ]]; then
+    {
+      echo -e "\n---- Other notes ----\n"
+      echo "$DIFFMESSAGE"
+    } >>"$EVENTLOG"
 
-  # Or the number of snapshots 
-  elif [ "$BACKUPOPTION" == "snap" ]; then
-    echo -e "\n---- Other notes ----\n" >> $EVENTLOG
-    SNAPSHOTNUMBER=$(find $TARGET -maxdepth 1 -type d | sort | grep -c '\<[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}T[0-9]\{2\}\.[0-9]\{2\}\.[0-9]\{2\}\>')
-    if [ $SNAPSHOTNUMBER -eq 1 ]; then
-      echo -e "This is the first full backup" >> $EVENTLOG
+  # Or the number of snapshots
+  elif [[ "$BACKUPOPTION" == "snap" ]]; then
+    echo -e "\n---- Other notes ----\n" >>"$EVENTLOG"
+    SNAPSHOTNUMBER=$(find "$TARGET" -maxdepth 1 -type d | sort | grep -c '\<[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}T[0-9]\{2\}\.[0-9]\{2\}\.[0-9]\{2\}\>')
+
+    if [[ "$SNAPSHOTNUMBER" -eq 1 ]]; then
+      echo -e "This is the first full backup" >>"$EVENTLOG"
     else
-      echo -e "There exist $SNAPSHOTNUMBER snapshots at the destination" >> $EVENTLOG
+      echo -e "There exist $SNAPSHOTNUMBER snapshots at the destination" >>"$EVENTLOG"
     fi
   fi
 
   # Show the last few lines of the rsync command
-  echo -e "\n---- Transfer Summary ----" >> $EVENTLOG
-  cat $TRANSFERLOG | tail -n 15 >> $EVENTLOG
-  
-  # Show drive usage
-  echo -e "\n---- Drive Map  ----\n" >> $EVENTLOG
-  df -ah >> $EVENTLOG
-  
+  {
+    echo -e "\n---- Transfer Summary ----"
+    tail -n 15 <"$TRANSFERLOG"
+
+    # Show drive usage
+    echo -e "\n---- Drive Map  ----\n"
+    df -ah
+  } >>"$EVENTLOG"
+
   # Email if specified
-  if [ "$EMAILADDRESS" != "" ]; then
-    mailreport $EMAILADDRESS "$EMAILSUBJECT" $EVENTLOG
-  elif [ "$BEQUIET" == "false" ]; then
-    cat $EVENTLOG
+  if [[ "$EMAILADDRESS" != "" ]]; then
+    mailreport "$EMAILADDRESS" "$EMAILSUBJECT" "$EVENTLOG"
+  elif [[ "$BEQUIET" == "false" ]]; then
+    cat "$EVENTLOG"
   fi
 
   # Copy log files to their intended destination and compress them
-  mv $EVENTLOG $SHORTLOG
-  mv $TRANSFERLOG $LONGLOG
-  gzip -9 $SHORTLOG $LONGLOG
+  mv "$EVENTLOG" "$SHORTLOG"
+  mv "$TRANSFERLOG" "$LONGLOG"
+  gzip -9 "$SHORTLOG" "$LONGLOG"
 
   # Finally, move the 'latest' symlink
-  if [ -s 'latest' ]; then
-    if [ "$BACKUPOPTION" == "sync" ]; then
+  if [[ -s 'latest' ]]; then
+    if [[ "$BACKUPOPTION" == "sync" ]]; then
       LASTSYNCPATH=$(resolve_link latest)
-      mv $LASTSYNCPATH $TARGET/$TIME_STARTED
+      mv "$LASTSYNCPATH" "$TARGET/$TIME_STARTED"
     fi
     rm 'latest'
   fi
-  ln -s $TIME_STARTED 'latest'
+  ln -s "$TIME_STARTED" 'latest'
 
 # Errors encountered, so:
 else
 
   # Rename the target directory
-  mv $TIME_STARTED $TIME_STARTED.incomplete
-  
+  mv "$TIME_STARTED" "$TIME_STARTED.incomplete"
+
   # Prepare depressing email subject
-  EMAILSUBJECT="eror - `hostname -s`" 
-  
+  EMAILSUBJECT="eror - $(hostname -s)"
+
   # Log error
   ERRORDESCRIPTION=$(expand_rsync_exit_code $RSYNCEXITCODE)
-  send_log_param "Exit Code"   "$RSYNCEXITCODE"    >> $EVENTLOG
-  send_log_param "Description" "$ERRORDESCRIPTION" >> $EVENTLOG
-  send_log_param "Error File"  "$EVENTLOG"         >> $EVENTLOG
-  echo -e "\nThe backup script encountered an error. The error log specified above has not been removed." >> $EVENTLOG
-  
-  # Spit error output
-  echo -e "\n ---- Raw error output (last 15 lines) ----\n" >> $EVENTLOG
-  cat $TRANSFERLOG | tail -n 15 >> $EVENTLOG
-  
+
+  # shellcheck disable=SC2094
+  {
+    send_log_param "Exit Code" "$RSYNCEXITCODE"
+    send_log_param "Description" "$ERRORDESCRIPTION"
+
+    # shellcheck disable=SC2094
+    send_log_param "Error File" "$EVENTLOG"
+    echo -e "\nThe backup script encountered an error. The error log specified above has not been removed."
+
+    # Spit error output
+    echo -e "\n ---- Raw error output (last 15 lines) ----\n"
+    tail -n 15 <"$TRANSFERLOG"
+  } >>"$EVENTLOG"
+
   # Finish the catalog
-  printf "%-22s\n" "No" >> $CATALOG
-  if [ "$EMAILADDRESS" != "" ]; then
-    mailreport $EMAILADDRESS "$EMAILSUBJECT" $EVENTLOG
-  elif [ "$BEQUIET" == "false" ]; then
-    cat $EVENTLOG
+  printf "%-22s\n" "No" >>"$CATALOG"
+  if [[ "$EMAILADDRESS" != "" ]]; then
+    mailreport "$EMAILADDRESS" "$EMAILSUBJECT" "$EVENTLOG"
+  elif [[ "$BEQUIET" == "false" ]]; then
+    cat "$EVENTLOG"
   fi
 
 fi
diff --git a/prune b/prune
--- a/prune
+++ b/prune
@@ -1,19 +1,19 @@
 #!/bin/bash
 
-# Maintain 'n' number of snapshots at any given time. 
+# Maintain 'n' number of snapshots at any given time.
 # Complimentary to backup
 # https://github.com/afreeorange/rsync-timemachine
 
 # Nikhil Anand <anand.nikhil@gmail.com>
 # Mon Oct 25 09:22:28 CDT 2010
 
-# General purpose mailer subroutine. 
+# General purpose mailer subroutine.
 mailreport() {
   EMAILADDRESS=$1
   SUBJECT=$2
   MESSAGEFILE=$3
 
-  mail -s "$SUBJECT" $EMAILADDRESS < $MESSAGEFILE
+  mail -s "$SUBJECT" "$EMAILADDRESS" <"$MESSAGEFILE"
 }
 
 # Emulate the 'seq' command for OS X. This _could_ be done with 'jot', but I'm le lazy.
@@ -21,15 +21,15 @@ _seq() {
   counter="$1"
   max="$2"
 
-  if [ "$#" -eq 2 ] ; then
+  if [ "$#" -eq 2 ]; then
     step=1
   else
     step=$3
   fi
 
-  while [ $counter -le $max ] ; do
-    echo $counter
-    counter=$(expr $counter + $step)
+  while [[ $counter -le $max ]]; do
+    echo "$counter"
+    counter=$((counter + step))
   done
 
   return 0
@@ -43,7 +43,7 @@ send_log_param() {
 # Show script usage information
 usage() {
   echo -e "
-`basename $0` [OPTIONS]
+$(basename "$0") [OPTIONS]
 
 Options
  -d   backup directory containing snapshots
@@ -56,43 +56,41 @@ Options
 }
 
 # Show usage if no params
-if [ $# -eq 0 ]; then
-  usage
-fi
+[[ $# -eq 0 ]] && usage
 
 # Start collecting rotation params
 BEQUIET=false
 EMAILADDRESS=""
 while getopts "d:n:rm:q" opt; do
   case $opt in
-    d)
-      SNAPSHOT_FOLDER=$OPTARG
-      ;;
-    n)
-      NUMBER_TO_KEEP=$OPTARG
-      ;;
-    r)
-      DELETE_ROTATION_LOGS=true
-      ;;
-    m)
-      EMAILADDRESS=$OPTARG
-      ;;
-    q)
-      BEQUIET=true
-      ;;
-    \?)
-      echo "Invalid option: -$OPTARG" >&2
-      exit 1
-      ;;
-    :)
-      echo "Option -$OPTARG requires an argument." >&2
-      exit 1
-      ;;
+  d)
+    SNAPSHOT_FOLDER=$OPTARG
+    ;;
+  n)
+    NUMBER_TO_KEEP=$OPTARG
+    ;;
+  r)
+    DELETE_ROTATION_LOGS=true
+    ;;
+  m)
+    EMAILADDRESS=$OPTARG
+    ;;
+  q)
+    BEQUIET=true
+    ;;
+  \?)
+    echo "Invalid option: -$OPTARG" >&2
+    exit 1
+    ;;
+  :)
+    echo "Option -$OPTARG requires an argument." >&2
+    exit 1
+    ;;
   esac
 done
 
 # Log the start time
-TIME_STARTED=`date "+%Y-%m-%dT%H.%M.%S"`
+TIME_STARTED=$(date "+%Y-%m-%dT%H.%M.%S")
 
 # Set the internal file separator since we're using arrays
 IFS='
@@ -100,78 +98,83 @@ IFS='
 
 # Define log files, process lock, etc
 ROTATELOG="/tmp/rotatelog.$TIME_STARTED"
-DELETELOG=$(mktemp $ROTATELOG.XXXXXX)
+DELETELOG=$(mktemp "$ROTATELOG.XXXXXX")
 LOCKFILE="/tmp/rotatelock"
 SOURCESERVER=$(hostname -s)
 CATALOG="$SNAPSHOT_FOLDER/logs/catalog"
 
 # Start logging
-send_log_param "Started"     "$TIME_STARTED"    >> $ROTATELOG
-send_log_param "Backup path" "$SNAPSHOT_FOLDER" >> $ROTATELOG
+send_log_param "Started" "$TIME_STARTED" >>"$ROTATELOG"
+send_log_param "Backup path" "$SNAPSHOT_FOLDER" >>"$ROTATELOG"
 
 ###### BEGIN SANITY CHECK #####
 
 # Show usage if snapshot folder's not specified
-if [ -z $SNAPSHOT_FOLDER ]; then
+if [[ -z $SNAPSHOT_FOLDER ]]; then
   usage
 fi
 
-# Check for the existence of the backup folder 
-if [ ! -d $SNAPSHOT_FOLDER ]; then
-  echo -e "\nCould not find source $SNAPSHOT_FOLDER" >> $ROTATELOG
-  if [ ! -z $EMAILADDRESS ]; then
-    mailreport $EMAILADDRESS "eror - $SOURCESERVER" $ROTATELOG
-  elif [ ! -z $BEQUIET ]; then
-    more $ROTATELOG
+# Check for the existence of the backup folder
+if [[ ! -d $SNAPSHOT_FOLDER ]]; then
+  echo -e "\nCould not find source $SNAPSHOT_FOLDER" >>"$ROTATELOG"
+  if [[ -n $EMAILADDRESS ]]; then
+    mailreport "$EMAILADDRESS" "eror - $SOURCESERVER" "$ROTATELOG"
+  elif [[ -n $BEQUIET ]]; then
+    more "$ROTATELOG"
   fi
   exit 1
 fi
 
 # Check the number of snapshots specified
-if [ -z $NUMBER_TO_KEEP ]; then
+if [[ -z $NUMBER_TO_KEEP ]]; then
   NUMBER_TO_KEEP=10
 fi
 case "$NUMBER_TO_KEEP" in
-  *[!0-9]*) NUMBER_TO_KEEP=10 ;;
-         0) NUMBER_TO_KEEP=10
+*[!0-9]*) NUMBER_TO_KEEP=10 ;;
+0) NUMBER_TO_KEEP=10 ;;
 esac
 
 # Generate a list of ISO timestamps. Will be used to find and delete snapshots and log files
-LIST_OF_TIMESTAMPS=($(find $SNAPSHOT_FOLDER -maxdepth 1 -type d -exec basename {} \;| sort | grep '\<[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}T[0-9]\{2\}\.[0-9]\{2\}\.[0-9]\{2\}\>'))
+# shellcheck disable=SC2207
+LIST_OF_TIMESTAMPS=($(find "$SNAPSHOT_FOLDER" -maxdepth 1 -type d -exec basename {} \; | sort | grep '\<[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}T[0-9]\{2\}\.[0-9]\{2\}\.[0-9]\{2\}\>'))
 NUMBER_OF_SNAPSHOTS=${#LIST_OF_TIMESTAMPS[@]}
 
-send_log_param "Snapshots" "$NUMBER_OF_SNAPSHOTS" >> $ROTATELOG
-send_log_param "Keep"      "$NUMBER_TO_KEEP"      >> $ROTATELOG
+{
+  send_log_param "Snapshots" "$NUMBER_OF_SNAPSHOTS"
+  send_log_param "Keep" "$NUMBER_TO_KEEP"
+} >>"$ROTATELOG"
 
 # Check if any backup entities exist in source dir
-if [ $NUMBER_OF_SNAPSHOTS -eq "0" ]; then
-  echo -e "\nNo backup entities found in the specified directory ($SNAPSHOT_FOLDER)" >> $ROTATELOG
+if [[ $NUMBER_OF_SNAPSHOTS -eq "0" ]]; then
+  echo -e "\nNo backup entities found in the specified directory ($SNAPSHOT_FOLDER)" >>"$ROTATELOG"
   exit 1
 else
   # More snapshots than existing directories?
-  if [ $NUMBER_TO_KEEP -gt $NUMBER_OF_SNAPSHOTS ]; then
-    echo -e "\nYou wanted to keep $NUMBER_TO_KEEP snapshots out of $NUMBER_OF_SNAPSHOTS. Kinda not possible." >> $ROTATELOG
+  if [[ $NUMBER_TO_KEEP -gt $NUMBER_OF_SNAPSHOTS ]]; then
+    echo -e "\nYou wanted to keep $NUMBER_TO_KEEP snapshots out of $NUMBER_OF_SNAPSHOTS. Kinda not possible." >>"$ROTATELOG"
     exit 1
-  elif [ $NUMBER_TO_KEEP -eq $NUMBER_OF_SNAPSHOTS ]; then
-    echo -e "\nYou want to delete $NUMBER_TO_KEEP out of $NUMBER_OF_SNAPSHOTS snapshots? Why not just remove the backup directory and be done? Why mess with me?" >> $ROTATELOG
+  elif [[ $NUMBER_TO_KEEP -eq $NUMBER_OF_SNAPSHOTS ]]; then
+    echo -e "\nYou want to delete $NUMBER_TO_KEEP out of $NUMBER_OF_SNAPSHOTS snapshots? Why not just remove the backup directory and be done? Why mess with me?" >>"$ROTATELOG"
     exit 1
   fi
 fi
-  
-# Check platform and set the seq command 
+
+# Check platform and set the seq command
 SEQUENCE=_seq
-if [ `uname` == "Linux" ]; then
+if [[ "$(uname)" == "Linux" ]]; then
   SEQUENCE=$(which seq)
 fi
 
 # Check if a competing backup process exists
-if [ -e "$LOCKFILE" ]; then
-  echo -e "\nAnother rotation job exists for the same client. Aborting." >> $ROTATELOG
-  if [ "$EMAILADDRESS" != "" ]; then
-    mailreport $EMAILADDRESS "eror - $SOURCESERVER" $ROTATELOG
-  elif [ "$BEQUIET" == "false" ]; then
-    more $ROTATELOG
+if [[ -e "$LOCKFILE" ]]; then
+  echo -e "\nAnother rotation job exists for the same client. Aborting." >>"$ROTATELOG"
+
+  if [[ "$EMAILADDRESS" != "" ]]; then
+    mailreport "$EMAILADDRESS" "eror - $SOURCESERVER" "$ROTATELOG"
+  elif [[ "$BEQUIET" == "false" ]]; then
+    more "$ROTATELOG"
   fi
+
   exit 1
 else
   touch $LOCKFILE
@@ -180,45 +183,47 @@ fi
 ###### END SANITY CHECK ######
 
 # Seems like everything is okay; start deleting. Create a temporary deletion log
-echo -e "\n---- Removal Log ----\n" >> $DELETELOG
-CLEAN_TO_INDEX=$(( NUMBER_OF_SNAPSHOTS - NUMBER_TO_KEEP - 1 ))
+echo -e "\n---- Removal Log ----\n" >>"$DELETELOG"
+CLEAN_TO_INDEX=$((NUMBER_OF_SNAPSHOTS - NUMBER_TO_KEEP - 1))
+
 for i in $($SEQUENCE 0 $CLEAN_TO_INDEX); do
-  rm -rf $SNAPSHOT_FOLDER/${LIST_OF_TIMESTAMPS[i]}                        2>> $DELETELOG
-  echo "Removed" $SNAPSHOT_FOLDER/${LIST_OF_TIMESTAMPS[i]}                 >> $DELETELOG
+  # shellcheck disable=SC2129,SC2115
+  rm -rf "$SNAPSHOT_FOLDER"/"${LIST_OF_TIMESTAMPS[i]}" 2>>"$DELETELOG"
+  echo "Removed" "$SNAPSHOT_FOLDER/${LIST_OF_TIMESTAMPS[i]}" >>"$DELETELOG"
 
-  rm -rf $SNAPSHOT_FOLDER/logs/backuplog.${LIST_OF_TIMESTAMPS[i]}.gz      2>> $DELETELOG
-  echo "       " $SNAPSHOT_FOLDER/logs/${LIST_OF_TIMESTAMPS[i]}.full.gz    >> $DELETELOG
+  rm -rf "$SNAPSHOT_FOLDER/logs/backuplog.${LIST_OF_TIMESTAMPS[i]}.gz" 2>>"$DELETELOG"
+  echo "       " "$SNAPSHOT_FOLDER/logs/${LIST_OF_TIMESTAMPS[i]}.full.gz" >>"$DELETELOG"
 
-  rm -rf $SNAPSHOT_FOLDER/logs/backuplog.${LIST_OF_TIMESTAMPS[i]}.full.gz 2>> $DELETELOG
-  echo "       " $SNAPSHOT_FOLDER/logs/${LIST_OF_TIMESTAMPS[i]}.gz         >> $DELETELOG
+  rm -rf "$SNAPSHOT_FOLDER/logs/backuplog.${LIST_OF_TIMESTAMPS[i]}.full.gz" 2>>"$DELETELOG"
+  echo "       " "$SNAPSHOT_FOLDER/logs/${LIST_OF_TIMESTAMPS[i]}.gz" >>"$DELETELOG"
 done
 
 # Remove older rotation logs
-if [ ! -z $DELETE_ROTATION_LOGS ]; then
-  rm -rf $SNAPSHOT_FOLDER/logs/rotatelog* 2>> $DELETELOG
+if [[ -n $DELETE_ROTATION_LOGS ]]; then
+  rm -rf "$SNAPSHOT_FOLDER"/logs/rotatelog* 2>>"$DELETELOG"
 fi
 
 # Log finish time
-TIME_FINISHED=`date "+%Y-%m-%dT%H.%M.%S"`
-send_log_param "Finished" "$TIME_FINISHED" >> $ROTATELOG
+TIME_FINISHED=$(date "+%Y-%m-%dT%H.%M.%S")
+send_log_param "Finished" "$TIME_FINISHED" >>"$ROTATELOG"
 
 # Finish the rotation log
-cat $DELETELOG >> $ROTATELOG
+cat "$DELETELOG" >>"$ROTATELOG"
 
 # Email if specified
-if [ "$EMAILADDRESS" != "" ]; then
-  mailreport $EMAILADDRESS "$EMAILSUBJECT" $ROTATELOG
-elif [ "$BEQUIET" == "false" ]; then
-  cat $ROTATELOG
+if [[ "$EMAILADDRESS" != "" ]]; then
+  mailreport "$EMAILADDRESS" "$EMAILSUBJECT" "$ROTATELOG"
+elif [[ "$BEQUIET" == "false" ]]; then
+  cat "$ROTATELOG"
 fi
 
 # Clean up
-rm -f $DELETELOG
-mv $ROTATELOG $SNAPSHOT_FOLDER/logs/rotatelog.$TIME_STARTED
-gzip -9 $SNAPSHOT_FOLDER/logs/rotatelog.$TIME_STARTED
+rm -f "$DELETELOG"
+mv "$ROTATELOG" "$SNAPSHOT_FOLDER/logs/rotatelog.$TIME_STARTED"
+gzip -9 "$SNAPSHOT_FOLDER/logs/rotatelog.$TIME_STARTED"
 
 # Finish the catalog
-printf "%-22s%-22s%-22s(%d,%d)\n" "prune" $TIME_STARTED $TIME_FINISHED $NUMBER_OF_SNAPSHOTS $NUMBER_TO_KEEP >> $CATALOG
+printf "%-22s%-22s%-22s(%d,%d)\n" "prune" "$TIME_STARTED" "$TIME_FINISHED" "$NUMBER_OF_SNAPSHOTS" "$NUMBER_TO_KEEP" >>"$CATALOG"
 
 # Remove lock
 rm $LOCKFILE
